[package]
name = "g2r"
version = "0.1.0"
authors = ["sauce"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libg2c-sys = { path="libg2c-sys", version="0.1.0" }
csv = "1.1"
chrono = "0.4"
text_io = "0.1.8"